#!/usr/bin/env dotnet fsi

// Generalized post-processor for OpenAPI discriminator schemas.
// Generates F# discriminated unions where Hawaii produces a list<itemType>
// referencing a type that doesn't exist in the generated output.
//
// Usage:
//   dotnet fsi discriminators.fsx <Types.fs> --list-type <name> --item-type <name> --kind-prefix <name>
//
// Example:
//   dotnet fsi discriminators.fsx Generated-Workers/Types.fs \
//     --list-type workersbindings \
//     --item-type workersbindingitem \
//     --kind-prefix workersbindingkind

open System
open System.IO
open System.Text.RegularExpressions

// ── Argument Parsing ─────────────────────────────────────────────

type Config =
    { TypesFile: string
      ListType: string
      ItemType: string
      KindPrefix: string }

let parseArgs (args: string[]) =
    let mutable typesFile = ""
    let mutable listType = ""
    let mutable itemType = ""
    let mutable kindPrefix = ""
    let mutable i = 0

    while i < args.Length do
        match args.[i] with
        | "--list-type" when i + 1 < args.Length ->
            listType <- args.[i + 1]
            i <- i + 2
        | "--item-type" when i + 1 < args.Length ->
            itemType <- args.[i + 1]
            i <- i + 2
        | "--kind-prefix" when i + 1 < args.Length ->
            kindPrefix <- args.[i + 1]
            i <- i + 2
        | s when not (s.StartsWith("--")) && typesFile = "" ->
            typesFile <- s
            i <- i + 1
        | other ->
            eprintfn "Unknown argument: %s" other
            exit 1

    if typesFile = "" || listType = "" || itemType = "" || kindPrefix = "" then
        eprintfn "Usage: dotnet fsi discriminators.fsx <Types.fs> --list-type <name> --item-type <name> --kind-prefix <name>"
        exit 1

    { TypesFile = typesFile
      ListType = listType
      ItemType = itemType
      KindPrefix = kindPrefix }

// ── Core Logic ──────────────────────────────────────────────────

let sanitizeCaseName (prefix: string) (typeName: string) =
    let raw = typeName.Substring(prefix.Length)
    if raw.Length > 0 then
        Char.ToUpper(raw.[0]).ToString() + raw.Substring(1)
    else
        typeName

let findKindTypes (content: string) (kindPrefix: string) =
    let pattern = sprintf @"type (%s[a-z0-9_]+)\s*=" (Regex.Escape kindPrefix)
    Regex.Matches(content, pattern)
    |> Seq.cast<Match>
    |> Seq.map (fun m -> m.Groups.[1].Value)
    // Exclude auxiliary types like *Type enums that are properties, not union cases
    |> Seq.filter (fun name ->
        not (name.EndsWith("Type", StringComparison.OrdinalIgnoreCase)))
    |> Seq.toList

let generateDiscriminatedUnion (itemType: string) (cases: (string * string) list) =
    let header = "// Discriminated union (auto-generated by post-processor)"
    let typeDecl = sprintf "type %s =" itemType
    let unionCases =
        cases
        |> List.map (fun (caseName, schemaType) ->
            sprintf "    | %s of %s" caseName schemaType)
        |> String.concat "\n"
    sprintf "%s\n%s\n%s\n" header typeDecl unionCases

let insertBefore (content: string) (anchor: string) (insertion: string) =
    let idx = content.IndexOf(anchor)
    if idx < 0 then
        None
    else
        Some (content.Substring(0, idx) + insertion + "\n" + content.Substring(idx))

// ── Main ────────────────────────────────────────────────────────

let args = fsi.CommandLineArgs |> Array.tail
let config = parseArgs args

printfn "Processing: %s" config.TypesFile
printfn "  list-type:   %s" config.ListType
printfn "  item-type:   %s" config.ItemType
printfn "  kind-prefix: %s" config.KindPrefix

if not (File.Exists config.TypesFile) then
    eprintfn "Error: File not found: %s" config.TypesFile
    exit 1

let content = File.ReadAllText(config.TypesFile)

// Idempotency check
if content.Contains(sprintf "type %s =" config.ItemType) then
    printfn "Already processed - %s type definition found" config.ItemType
    exit 0

// Find all kind types matching the prefix
let kindTypes = findKindTypes content config.KindPrefix

if List.isEmpty kindTypes then
    printfn "Warning: No types matching prefix '%s' found" config.KindPrefix
    exit 0

printfn "Found %d kind types" (List.length kindTypes)

// Build union cases
let cases =
    kindTypes
    |> List.map (fun typeName ->
        let caseName = sanitizeCaseName config.KindPrefix typeName
        (caseName, typeName))

// Generate the discriminated union code
let duCode = generateDiscriminatedUnion config.ItemType cases

// Find insertion point: type {listType} = list<{itemType}>
let anchor = sprintf "type %s = list<%s>" config.ListType config.ItemType

match insertBefore content anchor duCode with
| Some updated ->
    File.WriteAllText(config.TypesFile, updated)
    printfn "✓ Added discriminated union for %s (%d cases)" config.ItemType (List.length cases)
| None ->
    eprintfn "Error: Could not find insertion point: %s" anchor
    exit 1
